openapi: 3.0.3
info:
  title: Aunsorm KMS Service API
  version: 0.5.0
  description: |
    Planned key management service APIs.

    This spec is a placeholder for upcoming endpoints covering:
    - Key generation and lifecycle management
    - Key wrapping/unwrapping operations
    - Rotation policies and audit metadata
  contact:
    name: Aunsorm Security Team
  license:
    name: MIT

servers:
  - url: http://{host}:50014
    description: Deployment host (configure HOST in .env or your runtime environment)
    variables:
      host:
        default: aunsorm.local
        description: Hostname or IP address for the KMS service
  - url: http://aunsorm-kms:50014
    description: Docker Internal Network

tags:
  - name: Health
    description: Planned health status endpoints
  - name: Placeholder
    description: Placeholder tag for planned KMS endpoints

paths:
  /health:
    get:
      tags: [Health]
      summary: Health check
      description: Planned service health endpoint for KMS APIs.
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        '503':
          description: Service unavailable

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
