#!/usr/bin/env python3
"""Generate OpenAPI catalog artifacts for docs/api from openapi/*-service.yaml."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_DIR = ROOT / "openapi"
DOCS_API_DIR = ROOT / "docs" / "api"
MARKDOWN_OUT = DOCS_API_DIR / "openapi-catalog.md"
JSON_OUT = DOCS_API_DIR / "openapi-catalog.json"

REQUIRED_MARKERS = ("openapi:", "info:", "paths:")


@dataclass(frozen=True)
class OpenApiSpec:
    file_name: str
    service: str
    title: str
    version: str


def _extract_value(text: str, pattern: str, fallback: str) -> str:
    match = re.search(pattern, text, flags=re.MULTILINE)
    if match:
        return match.group(1).strip()
    return fallback


def parse_specs() -> list[OpenApiSpec]:
    specs: list[OpenApiSpec] = []

    for path in sorted(OPENAPI_DIR.glob("*-service.yaml")):
        text = path.read_text(encoding="utf-8")

        missing = [marker for marker in REQUIRED_MARKERS if marker not in text]
        if missing:
            markers = ", ".join(missing)
            raise SystemExit(f"{path.relative_to(ROOT)} is missing required sections: {markers}")

        service = path.stem.removesuffix("-service")
        title = _extract_value(text, r"^\s*title:\s*[\"']?([^\"'\n]+)[\"']?\s*$", f"{service} service")
        version = _extract_value(text, r"^\s*version:\s*[\"']?([^\"'\n]+)[\"']?\s*$", "unknown")

        specs.append(
            OpenApiSpec(
                file_name=path.name,
                service=service,
                title=title,
                version=version,
            )
        )

    if not specs:
        raise SystemExit("No openapi/*-service.yaml files found.")

    return specs


def write_markdown(specs: list[OpenApiSpec]) -> None:
    lines = [
        "# OpenAPI Catalog",
        "",
        "Auto-generated by `scripts/generate_openapi_catalog.py`. Do not edit manually.",
        "",
        "| Service | Title | Version | Spec | Swagger UI |",
        "|---|---|---|---|---|",
    ]

    for spec in specs:
        lines.append(
            "| `{service}` | {title} | `{version}` | [`{file}`](../../openapi/{file}) | "
            "[`Open`](../../openapi/index.html?spec={file}) |".format(
                service=spec.service,
                title=spec.title,
                version=spec.version,
                file=spec.file_name,
            )
        )

    MARKDOWN_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_json(specs: list[OpenApiSpec]) -> None:
    payload = {
        "generatedBy": "scripts/generate_openapi_catalog.py",
        "specs": [
            {
                "service": spec.service,
                "title": spec.title,
                "version": spec.version,
                "file": spec.file_name,
                "relativeSpecPath": f"openapi/{spec.file_name}",
            }
            for spec in specs
        ],
    }
    JSON_OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    DOCS_API_DIR.mkdir(parents=True, exist_ok=True)
    specs = parse_specs()
    write_markdown(specs)
    write_json(specs)
    print(f"Generated {MARKDOWN_OUT.relative_to(ROOT)} and {JSON_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
